### ISSUE TITLE
bug: unable to connect to testnet

### ISSUE THREAD

**Issue by NickFranceschina** [farcasterxyz/hub-monorepo#1127]
**What is the bug?**
Following the testnet docker setup (1.4.0), I am seeing logs as the hub appears to be syncing, but the status response only shows FID/Fname counts, yet always zero messages and "no peers"

```
hubble % docker compose exec hubble yarn status --insecure 
yarn run v1.22.19
$ node build/cli.js status --insecure
(node:194) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:194) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
{"level":30,"time":1689262995946,"pid":194,"hostname":"9256c22a9b91","msg":"Hub Version: 1.4.0 Messages: 0 FIDs: 16130 FNames: 16131}"}
{"level":30,"time":1689262995948,"pid":194,"hostname":"9256c22a9b91","msg":"Sync Status: No peers"}
Done in 1.18s.
```

I also see the following errors when starting up:
![photo_2023-07-13 12 48 26](https://github.com/farcasterxyz/hub-monorepo/assets/419831/fe2231c6-be29-4343-9fdf-bfb20d4212df)

I've tried this multiple times over the weekend and this week and had verified by another developer.  I'm able to directly connect to the bootstrap node's port using basic networking tools (like `telnet`) and it is open for me.  I'm feeling like perhaps testnet is actually peer-restricted but maybe nobody has noticed because everyone has moved over to mainnet??

I have not yet attempted to query my hub to see if it actually has any messages

**How can it be reproduced? (optional)**
following the Testnet setup directions in Hubble README

**Additional context (optional)**

**Comment by varunsrin** [comment]
should be fixed by: https://github.com/farcasterxyz/hub-monorepo/pull/1151

**Comment by Drewsapple** [comment]
I checked out 3664c6d and re-ran `docker compose up`, but the logs appear to show the same error:

```
hubble-hubble-1  | {"level":30,"time":1689527847445,"pid":27,"hostname":"00c4106acfe8","component":"FNameRegistryEventsProvider","msg":"Fetched 0 fname events upto 16285"}
hubble-hubble-1  | {"level":30,"time":1689527847447,"pid":27,"hostname":"00c4106acfe8","component":"SyncEngine","rootHash":"","msg":"Sync engine initialized"}
hubble-hubble-1  | {"level":30,"time":1689527847449,"pid":27,"hostname":"00c4106acfe8","component":"Node","function":"createNode","allowedPeerIds":[],"msg":"!!! PEER-ID RESTRICTIONS ENABLED !!!"}
hubble-hubble-1  | {"level":30,"time":1689527847527,"pid":27,"hostname":"00c4106acfe8","component":"Node","identity":"12D3KooWNG6ktRNyXKXuXawqCnXRBZHQeuiAGCkaMiYt7RbGd6Zk","addresses":["/ip4/75.139.73.214/tcp/2282/p2p/12D3KooWNG6ktRNyXKXuXawqCnXRBZHQeuiAGCkaMiYt7RbGd6Zk"],"msg":"Starting libp2p"}
hubble-hubble-1  | {"level":30,"time":1689527849008,"pid":27,"hostname":"00c4106acfe8","component":"ConnectionFilter","peerId":"12D3KooWQaNFSaNLfsa69QtDiwX9SNHV3VPqnRUeHXCuM3G8yknG","filter":"denyOutboundEncryptedConnection","msg":"denied a connection"}
hubble-hubble-1  | {"level":50,"time":1689527849010,"pid":27,"hostname":"00c4106acfe8","component":"Node","err":{"type":"AggregateError","message":"All promises were rejected","stack":"AggregateError: All promises were rejected","aggregateErrors":[{"type":"Error","message":"The multiaddr connection is blocked by gater.acceptEncryptedConnection","stack":"Error: The multiaddr connection is blocked by gater.acceptEncryptedConnection\n    at DefaultUpgrader.upgradeOutbound (file:///home/node/app/node_modules/libp2p/dist/src/upgrader.js:203:35)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async TCP.dial (file:///home/node/app/node_modules/@libp2p/tcp/dist/src/index.js:51:22)\n    at async DefaultTransportManager.dial (file:///home/node/app/node_modules/libp2p/dist/src/transport-manager.js:78:20)\n    at async DialRequest.dialAction (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:195:20)\n    at async file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/dial-request.js:67:28\n    at async Promise.any (index 0)\n    at async DialRequest.run (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/dial-request.js:53:20)\n    at async DefaultDialer.dial (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:107:32)\n    at async DefaultConnectionManager.openConnection (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/index.js:306:32)","code":"ERR_CONNECTION_INTERCEPTED"}]},"msg":"Failed to connect to peer at address: /dns/testnet1.farcaster.xyz/tcp/2282"}
hubble-hubble-1  | {"level":30,"time":1689527851265,"pid":27,"hostname":"00c4106acfe8","component":"EthEventsProvider","blockNumber":9356298,"msg":"new block: 9356298"}
```

Is there further config I need to do to connect to the testnet bootstrap node? @varunsrin

**Comment by varunsrin** [comment]
@Drewsapple the changes didn't get loaded since the upgrade process just pulled the most recent release which was v1.4.1. I just pushed v1.4.2 which should resolve this.

**Comment by Drewsapple** [comment]
@varunsrin Resolved! I think you can close. (BTW, I think adding "how to build the container from git" to the contributor guide would be very helpful. Adding my own log statements would have really helped me debug, and trying to do so is what made me realize the container was out of date.)
