### ISSUE TITLE
test: EthEventsProvider › process events › handles new blocks is sometimes flaky

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#1149]
**What is the bug?**
Test fails sporadically

**How can it be reproduced? (optional)**=
Happens occasionally in CI

**Additional context (optional)**

```
@farcaster/hubble:test:ci: FAIL src/eth/ethEventsProvider.test.ts (11.566 s)
@farcaster/hubble:test:ci:   ● EthEventsProvider › process events › handles new blocks
@farcaster/hubble:test:ci: 
@farcaster/hubble:test:ci:     thrown: "Exceeded timeout of 5000 ms for a test.
@farcaster/hubble:test:ci:     Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
@farcaster/hubble:test:ci: 
@farcaster/hubble:test:ci:       140 |     };
@farcaster/hubble:test:ci:       141 |
@farcaster/hubble:test:ci:     > 142 |     test("handles new blocks", async () => {
@farcaster/hubble:test:ci:           |     ^
@farcaster/hubble:test:ci:       143 |       await testClient.mine({ blocks: 1 });
@farcaster/hubble:test:ci:       144 |       const latestBlockNumber = await publicClient.getBlockNumber();
@farcaster/hubble:test:ci:       145 |       await waitForBlock(Number(latestBlockNumber));
@farcaster/hubble:test:ci: 
@farcaster/hubble:test:ci:       at test (src/eth/ethEventsProvider.test.ts:142:5)
@farcaster/hubble:test:ci:       at describe (src/eth/ethEventsProvider.test.ts:108:3)
@farcaster/hubble:test:ci:       at describe (src/eth/ethEventsProvider.test.ts:53:1)
@farcaster/hubble:test:ci: 
@farcaster/hubble:test:ci: 
@farcaster/hubble:test:ci: Test Suites: 1 failed, 48 passed, 49 total
@farcaster/hubble:test:ci: Tests:       1 failed, 1 skipped, 714 passed, 716 total
@farcaster/hubble:test:ci: Snapshots:   0 total
@farcaster/hubble:test:ci: Time:        54.231 s
@farcaster/hubble:test:ci: Ran all test suites.
```

**Comment by varunsrin** [comment]
@CassOnMars assigning to you in case related to recent changes with eth event ingestion

**Comment by varunsrin** [comment]
No longer an issue
