### ISSUE TITLE
Installation via Docker failing in step 3.

### ISSUE THREAD

**Issue by Huge** [farcasterxyz/hub-monorepo#1370]
I have followed https://www.thehubble.xyz/intro/install.html#install-via-docker to install the Hub on my Debian, here is what happened on the command provided:
```
➜  hubble git:(main) docker compose run hubble yarn identity create
WARN[0000] The "ETH_MAINNET_RPC_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "OPTIMISM_L2_RPC_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STATSD_METRICS_SERVER" variable is not set. Defaulting to a blank string. 
[+] Creating 1/1
 ✔ Network hubble_my-network  Created                                                          0.1s 
[+] Running 3/3
 ✔ hubble 2 layers [⣿⣿]      0B/0B      Pulled                                                43.8s 
   ✔ 69704cea5847 Pull complete                                                               39.9s 
   ✔ bd9ddc54bea9 Pull complete                                                               40.2s 
yarn run v1.22.19
$ node --no-warnings build/cli.js identity create
file:///home/node/app/apps/hubble/build/cli.js:526
        throw new Error(err);
              ^

Error: Error: EACCES: permission denied, open '/home/node/app/apps/hubble/.hub/default_id.protobuf'
    at writePeerId (file:///home/node/app/apps/hubble/build/cli.js:526:15)
    at async Command.<anonymous> (file:///home/node/app/apps/hubble/build/cli.js:539:13)

Node.js v20.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Additional context:**
```
➜  hubble git:(main) lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
➜  hubble git:(main) docker -v
Docker version 20.10.5+dfsg1, build 55c4c88
```

~~Might be related to https://github.com/farcasterxyz/hub-monorepo/issues/1288~~

**Comment by varunsrin** [comment]
You need to set permissions for the docker container to write to .hub and .rocks.

Recommend using the install script which handles a lot of this automatically: https://www.thehubble.xyz/intro/install.html

**Comment by timjrobinson** [comment]
Still seeing this error following the docs. Where should these .hub and .rocks folders be located and what permissions do they need? Should be added to the docs, as the current steps don't work when following them.

**Comment by timjrobinson** [comment]
Fix is to run `sudo chmod a+rw .hub .rocks` in the `apps/hubble` folder.
