### ISSUE TITLE
Hub fails to sync L2 Farcaster contracts

### ISSUE THREAD

**Issue by christopherwxyz** [farcasterxyz/hub-monorepo#1373]
**What is the bug?**

When attempting to run or upgrade an existing hub using the latest hubble build, the Hub will fail with the following:

```
hubble-hubble-1   |  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   0% | Syncing Farcaster L2 Contracts | 0/27147 | ETA: NFs
hubble-hubble-1   |
hubble-hubble-1   |
hubble-hubble-1   | {
  "level": 60,
  "time": 1694305511389,
  "pid": 1,
  "hostname": "de9d6f1b6ce9",
  "err": {
    "type": "Error",
    "message": "Failed to start hub: Method is not implemented.\n\nURL: https://optimism-mainnet.infura.io/v3/MY_INFURA_API_KEY\nRequest body: {\"method\":\"eth_newFilter\",\"params\":[{\"address\":\"0x00000000fcaf86937e41ba038b4fa40baa4b780a\",\"fromBlock\":\"0x6842e56\",\"toBlock\":\"0x684323e\"}]}\n\nDetails: method not supported eth_newFilter\nVersion: viem@1.1.4: Method is not implemented.\n\nURL: https://optimism-mainnet.infura.io/v3/MY_INFURA_API_KEY\nRequest body: {\"method\":\"eth_newFilter\",\"params\":[{\"address\":\"0x00000000fcaf86937e41ba038b4fa40baa4b780a\",\"fromBlock\":\"0x6842e56\",\"toBlock\":\"0x684323e\"}]}\n\nDetails: method not supported eth_newFilter\nVersion: viem@1.1.4: RPC Request failed.\n\nURL: https://optimism-mainnet.infura.io/v3/MY_INFURA_API_KEY\nRequest body: {\"method\":\"eth_newFilter\",\"params\":[{\"address\":\"0x00000000fcaf86937e41ba038b4fa40baa4b780a\",\"fromBlock\":\"0x6842e56\",\"toBlock\":\"0x684323e\"}]}\n\nDetails: method not supported eth_newFilter\nVersion: viem@1.1.4: method not supported eth_newFilter",
    "stack": "Error: Failed to start hub\n    at file:///home/node/app/apps/hubble/build/cli.js:475:75\n    at /home/node/app/node_modules/neverthrow/dist/index.cjs.js:113:102\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Command.<anonymous> (file:///home/node/app/apps/hubble/build/cli.js:475:25)\ncaused by: MethodNotSupportedRpcError: Method is not implemented.\n\nURL: https://optimism-mainnet.infura.io/v3/MY_INFURA_API_KEY\nRequest body: {\"method\":\"eth_newFilter\",\"params\":[{\"address\":\"0x00000000fcaf86937e41ba038b4fa40baa4b780a\",\"fromBlock\":\"0x6842e56\",\"toBlock\":\"0x684323e\"}]}\n\nDetails: method not supported eth_newFilter\nVersion: viem@1.1.4\n    at withRetry.delay.count.count (file:///home/node/app/node_modules/viem/dist/esm/utils/buildRequest.js:49:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async attemptRetry (file:///home/node/app/node_modules/viem/dist/esm/utils/promise/withRetry.js:12:30)\ncaused by: MethodNotSupportedRpcError: Method is not implemented.\n\nURL: https://optimism-mainnet.infura.io/v3/MY_INFURA_API_KEY\nRequest body: {\"method\":\"eth_newFilter\",\"params\":[{\"address\":\"0x00000000fcaf86937e41ba038b4fa40baa4b780a\",\"fromBlock\":\"0x6842e56\",\"toBlock\":\"0x684323e\"}]}\n\nDetails: method not supported eth_newFilter\nVersion: viem@1.1.4\n    at withRetry.delay.count.count (file:///home/node/app/node_modules/viem/dist/esm/utils/buildRequest.js:49:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async attemptRetry (file:///home/node/app/node_modules/viem/dist/esm/utils/promise/withRetry.js:12:30)\ncaused by: RpcRequestError: RPC Request failed.\n\nURL: https://optimism-mainnet.infura.io/v3/MY_INFURA_API_KEY\nRequest body: {\"method\":\"eth_newFilter\",\"params\":[{\"address\":\"0x00000000fcaf86937e41ba038b4fa40baa4b780a\",\"fromBlock\":\"0x6842e56\",\"toBlock\":\"0x684323e\"}]}\n\nDetails: method not supported eth_newFilter\nVersion: viem@1.1.4\n    at request (file:///home/node/app/node_modules/viem/dist/esm/clients/transports/http.js:42:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async withRetry.delay.count.count (file:///home/node/app/node_modules/viem/dist/esm/utils/buildRequest.js:26:20)\n    at async attemptRetry (file:///home/node/app/node_modules/viem/dist/esm/utils/promise/withRetry.js:12:30)\ncaused by: "
  },
  "msg": "Failed to start hub"
}
```

**How can it be reproduced? (optional)**

1. Run hubble.sh
2. Fill in prompts with APIs provided by Infura.
3. Wait for everything to snapshot sync.
4. Progress bar will either be NFs or LLs, then fail. 

**Additional context (optional)**

I can observe calls to Infura, so it is not a network setup issue.

**Comment by adityapk00** [comment]
The issue seems to be `Details: method not supported eth_newFilter`

This is weird, cause Infura definitely supports this method: https://blog.infura.io/post/filters-support-over-https

Can you file this issue with Infura and see what's going on?

**Comment by varunsrin** [comment]
@adityapk00 should we throw an error if we detect an infura url in the setup script? given that we know this isn't working right now.

**Comment by christopherwxyz** [comment]
Infura does support this method, and i can see the metrics associated to it. perhaps there is a rate limit or throttling that's happening here?

happy to switch to Alchemy, but i suspect something is exhausting the calls before this error is thrown.

**Comment by saarw** [comment]
The RPC node listed on Alchemy's [homepage](https://www.alchemy.com/chain-connect/endpoints/optimism-optimism) **mainnet.optimism.io** does not seem to support this, but nodes under Alchemy's domain do seem to suppor it.

**Comment by horsefacts** [comment]
Either way, Viem should fall back to polling if `eth_newFilter` is unavailable. Investigating.

**Comment by horsefacts** [comment]
Update here: it seems some RPC providers (Infura, Optimism's public RPC) do not support `eth_newFilter` on Optimism. We've updated sync to fall back to using `eth_getLogs` if filters aren't supported.

Using filters will sync faster, so it's recommended to use a provider that supports them like Alchemy if you can, but Infura and other nodes will now work.
