### ISSUE TITLE
Initial L2 sync fails with Infura because too many results returned

### ISSUE THREAD

**Issue by SaulMoonves** [farcasterxyz/hub-monorepo#1703]
**What is the bug?**
I am setting up a hub for the first time. Initial sync of L2 contracts is failing causing the server to shut down. Here is the error message:

```
{"level":60,"time":1708006425106,"pid":5933,"hostname":"playground","err":{"type":"Error","message":"Failed to start hub: Request exceeds defined limit.\n\nURL: https://optimism-mainnet.infura.io/v3/<REDACTED>\nRequest body: {\"method\":\"eth_getLogs\",\"params\":[{\"address\":\"0x00000000Fc6c5F01Fc30151999387Bb99A9f489b\",\"topics\":[[\"0x8e700b803af43e14651431cd73c9fe7d11b131ad797576a70b893ce5766f65c3\",\"0x03732e5295a5bd18e6ef95b03b41aa8bcadae292a7ef40468144c7a727dfa8b5\",\"0x0a6387c9ea3628b88a633bb4f3b151770f70085117a15f9bf3787cda53f13d31\",\"0x38d16b8cac22d99fc7c124b9cd0de2d3fa1faef420bfe791d8c362d765e22700\",\"0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0\",\"0x62e78cea01bee320cd4e420270b5ea74000d11b0c9f74754ebdbfc544b05a258\",\"0xf6891c84a6c6af32a6d052172a8acc4c631b1d5057ffa2bc1da268b6938ea2da\",\"0xf2e19a901b0748d8b08e428d0468896a039ac751ec4fec49b44b7b9c28097e45\",\"0xf49aa3de84c4496d3a942511e6d2319eb43aff3afa8072a0cb18f9cc55a0359f\",\"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef\",\"0x5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8aa4e537bd38aeae4b073aa\"]],\"fromBlock\":\"0x6ab5ff7\",\"toBlock\":\"0x6ab60f0\"}]}\n\nDetails: query returned more than 10000 results. Try with this block range [0x6AB6016, 0x6AB607E].\nVersion: viem@1.12.2: Request exceeds defined limit.\n\nURL: https://optimism-mainnet.infura.io/v3/<REDACTED>\nRequest body: {\"method\":\"eth_getLogs\",\"params\":[{\"address\":\"0x00000000Fc6c5F01Fc30151999387Bb99A9f489b\",\"topics\":[[\"0x8e700b803af43e14651431cd73c9fe7d11b131ad797576a70b893ce5766f65c3\",\"0x03732e5295a5bd18e6ef95b03b41aa8bcadae292a7ef40468144c7a727dfa8b5\",\"0x0a6387c9ea3628b88a633bb4f3b151770f70085117a15f9bf3787cda53f13d31\",\"0x38d16b8cac22d99fc7c124b9cd0de2d3fa1faef420bfe791d8c362d765e22700\",\"0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0\",\"0x62e78cea01bee320cd4e420270b5ea74000d11b0c9f74754ebdbfc544b05a258\",\"0xf6891c84a6c6af32a6d052172a8acc4c631b1d5057ffa2bc1da268b6938ea2da\",\"0xf2e19a901b0748d8b08e428d0468896a039ac751ec4fec49b44b7b9c28097e45\",\"0xf49aa3de84c4496d3a942511e6d2319eb43aff3afa8072a0cb18f9cc55a0359f\",\"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef\",\"0x5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8aa4e537bd38aeae4b073aa\"]],\"fromBlock\":\"0x6ab5ff7\",\"toBlock\":\"0x6ab60f0\"}]}\n\nDetails: query returned more than 10000 results. Try with this block range [0x6AB6016, 0x6AB607E].\nVersion: viem@1.12.2: RPC Request failed.\n\nURL: https://optimism-mainnet.infura.io/v3/<REDACTED>\nRequest body: {\"method\":\"eth_getLogs\",\"params\":[{\"address\":\"0x00000000Fc6c5F01Fc30151999387Bb99A9f489b\",\"topics\":[[\"0x8e700b803af43e14651431cd73c9fe7d11b131ad797576a70b893ce5766f65c3\",\"0x03732e5295a5bd18e6ef95b03b41aa8bcadae292a7ef40468144c7a727dfa8b5\",\"0x0a6387c9ea3628b88a633bb4f3b151770f70085117a15f9bf3787cda53f13d31\",\"0x38d16b8cac22d99fc7c124b9cd0de2d3fa1faef420bfe791d8c362d765e22700\",\"0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0\",\"0x62e78cea01bee320cd4e420270b5ea74000d11b0c9f74754ebdbfc544b05a258\",\"0xf6891c84a6c6af32a6d052172a8acc4c631b1d5057ffa2bc1da268b6938ea2da\",\"0xf2e19a901b0748d8b08e428d0468896a039ac751ec4fec49b44b7b9c28097e45\",\"0xf49aa3de84c4496d3a942511e6d2319eb43aff3afa8072a0cb18f9cc55a0359f\",\"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef\",\"0x5db9ee0a495bf2e6ff9c91a7834c1ba4fdd244a5e8aa4e537bd38aeae4b073aa\"]],\"fromBlock\":\"0x6ab5ff7\",\"toBlock\":\"0x6ab60f0\"}]}\n\nDetails: query returned more than 10000 results. Try with this block range [0x6AB6016, 0x6AB607E].\nVersion: viem@1.12.2: query returned more than 10000 results. Try with this block range [0x6AB6016, 0x6AB607E].","stack":"Error: Failed to start hub\n    at file:///var/lib/farcaster/hub-monorepo/apps/hubble/build/cli.js:492:75\n    at /var/lib/farcaster/hub-monorepo/node_modules/neverthrow/dist/index.cjs.js:113:102\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Command.<anonymous> (file:///var/lib/farcaster/hub-monorepo/apps/hubble/build/cli.js:492:25)\ncaused by: LimitExceededRpcError: Request exceeds defined limit.\n\nURL: https://optimism-mainnet.infura.io/v3/<REDACTED>\nRequest body: {\"method\":\"eth_getLogs\",\"params\":[{\"address\":\"0x00000000Fc6c5F01F
```

It appears that too many blocks are being queried at once for Infura?

This is happening maybe halfway through sync `Syncing Farcaster L2 Contracts | 250/4309238`

**How can it be reproduced? (optional)**

On a fresh server

```
yarn start \
        --eth-mainnet-rpc-url "https://mainnet.infura.io/v3/<REDACTED>" \
        --l2-rpc-url "https://optimism-mainnet.infura.io/v3/<REDACTED>" \
        --hub-operator-fid <REDACTED> \
        --announce-ip <REDACTED> \
        --bootstrap /dns/nemes.farcaster.xyz/tcp/2282 /dns/hoyt.farcaster.xyz/tcp/2282
```

**Additional context (optional)**

**Comment by sds** [comment]
Thanks for the report! 

I wasn't able to reproduce this using my own Infura RPC URLs, but I didn't want to wait around for multiple hours for the L2 contract sync step to finish. In the meantime, hopefully #1796 addresses.

![Screenshot 2024-03-07 at 05 59 13@2x](https://github.com/farcasterxyz/hub-monorepo/assets/677877/9303c36c-ff82-4de7-909b-5dd4bb54a578)

**Comment by sds** [comment]
In the meantime, until the above PR is released you can specify `--chunk-size` and `--l2-chunk-size` manually to avoid this problem. Hope that helps!
