### ISSUE TITLE
Hub shuts down suddenly when golang example is executed.

### ISSUE THREAD

**Issue by lucasmenendez** [farcasterxyz/hub-monorepo#1720]
**What is the bug?**
I am trying to implement [this example](https://github.com/farcasterxyz/hub-monorepo/blob/main/packages/hub-web/examples/golang-submitmessage/main.go) to create a Golang farcaster bot ([here my code](https://github.com/vocdoni/votebot/blob/3439507946d3db05d96fc3bc4d2805bb84c3faa4/bot/api.go#L98)) but it kills my own hub.

**How can it be reproduced? (optional)**
Hub logs:

```
 {"level":30,"time":1708519891926,"pid":1,"hostname":"d07795f7c1bb","component":"Hub","eventId":405752594116608,"fid":332370,"type":"LINK_ADD","submittedMessage":{"timestamp":1708517273000,"hash":"0xde0a612e77868ef18852f0ea68ef1a6e1f257e72","fid":332370,"type":5},"source":"gossip","msg":"submitMessage success"}
hubble-hubble-1   | {"level":40,"time":1708519891956,"pid":1,"hostname":"d07795f7c1bb","component":"Hub","submittedMessage":{"timestamp":1708458779000,"hash":"0x2b6a3710a4f7ed676db7c6d384a4480075d5bbb3","fid":244128,"type":1},"source":"sync","errCode":"bad_request.prunable","source":"sync","msg":"submitMessage error: message would be pruned"}
hubble-hubble-1   | {"level":30,"time":1708519891956,"pid":1,"hostname":"d07795f7c1bb","component":"HttpAPIServer","msg":"Stopped http API server"}
hubble-hubble-1   | {"level":30,"time":1708519891956,"pid":1,"hostname":"d07795f7c1bb","component":"rpcServer","msg":"Force shutdown succeeded"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891958,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519891959,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":50,"time":1708519891966,"pid":1,"hostname":"d07795f7c1bb","component":"GossipNodeWorker","err":{"type":"Error","message":"The operation was aborted","stack":"CodeError: The operation was aborted\n    at DefaultDialer.createDialTarget (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:118:31)\n    at async DefaultDialer.dial (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:81:16)\n    at async DefaultConnectionManager.openConnection (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/index.js:310:32)\n    at async Libp2pNode.dial (file:///home/node/app/node_modules/libp2p/dist/src/libp2p.js:261:16)\n    at async LibP2PNode.connectAddress (file:///home/node/app/apps/hubble/build/network/p2p/gossipNodeWorker.js:214:26)\n    at async MessagePort.<anonymous> (file:///home/node/app/apps/hubble/build/network/p2p/gossipNodeWorker.js:458:28)"},"msg":"Failed to connect to peer at address: /dns/elen.hubs.neynar.com/tcp/2282"}
hubble-hubble-1   | {"level":50,"time":1708519891966,"pid":1,"hostname":"d07795f7c1bb","component":"GossipNodeWorker","err":{"type":"Error","message":"The operation was aborted","stack":"CodeError: The operation was aborted\n    at DefaultDialer.createDialTarget (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:118:31)\n    at async DefaultDialer.dial (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:81:16)\n    at async DefaultConnectionManager.openConnection (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/index.js:310:32)\n    at async Libp2pNode.dial (file:///home/node/app/node_modules/libp2p/dist/src/libp2p.js:261:16)\n    at async LibP2PNode.connectAddress (file:///home/node/app/apps/hubble/build/network/p2p/gossipNodeWorker.js:214:26)\n    at async MessagePort.<anonymous> (file:///home/node/app/apps/hubble/build/network/p2p/gossipNodeWorker.js:458:28)"},"msg":"Failed to connect to peer at address: /dns/tari.hubs.neynar.com/tcp/2282"}
hubble-hubble-1   | {"level":50,"time":1708519891966,"pid":1,"hostname":"d07795f7c1bb","component":"GossipNodeWorker","err":{"type":"Error","message":"The operation was aborted","stack":"CodeError: The operation was aborted\n    at DefaultDialer.createDialTarget (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:118:31)\n    at async DefaultDialer.dial (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:81:16)\n    at async DefaultConnectionManager.openConnection (file:///home/node/app/node_modules/libp2p/dist/src/connection-manager/index.js:310:32)\n    at async Libp2pNode.dial (file:///home/node/app/node_modules/libp2p/dist/src/libp2p.js:261:16)\n    at async LibP2PNode.connectAddress (file:///home/node/app/apps/hubble/build/network/p2p/gossipNodeWorker.js:214:26)\n    at async MessagePort.<anonymous> (file:///home/node/app/apps/hubble/build/network/p2p/gossipNodeWorker.js:458:28)"},"msg":"Failed to connect to peer at address: /ip4/34.232.175.239/tcp/42086"}
hubble-hubble-1   | {"level":50,"time":1708519891967,"pid":1,"hostname":"d07795f7c1bb","component":"GossipNode","peerIdStr":"12D3KooWBPXFPS656B76tCmbbX6PB4vunmQcd8F38MZjkR88ofBx","addr":"/ip4/34.232.175.239/tcp/42086","error":{"errCode":"unavailable","presentable":false,"name":"HubError"},"msg":"Failed to connect to peer from DB"}
hubble-hubble-1   | {"level":30,"time":1708519892007,"pid":1,"hostname":"d07795f7c1bb","component":"GossipNode","identity":"12D3KooWAJNSPjYG31YEWeszqzRmd5u6tAMQUuFDfoKSrBMnh6hp","msg":"Stopped libp2p..."}
hubble-hubble-1   | {"level":30,"time":1708519892198,"pid":1,"hostname":"d07795f7c1bb","component":"SyncMerkleTrieWorker","numDbUpdates":41967,"force":true,"msg":"Trie committed pending DB updates"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   |  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   0% | Starting Hubble | 0/30 | ETA:  0s
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","msg":"Interrupting sync"}
hubble-hubble-1   | {"level":30,"time":1708519892539,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","syncResult":{"total":5,"successCount":5,"deferredCount":0,"errCount":49},"msg":"Perform sync: Sync Complete"}
hubble-hubble-1   | {"level":30,"time":1708519892540,"pid":1,"hostname":"d07795f7c1bb","component":"SyncEngine","peerId":"12D3KooWFBk1zFVEeMk4YwUssPC2KSEyU714pikPX6b5yrb7aYnY","result":{"total":5,"successCount":5,"deferredCount":0,"errCount":49},"timeTakenMs":19506,"msg":"Diffsync: complete"}
hubble-hubble-1   | {"level":30,"time":1708519892700,"pid":1,"hostname":"d07795f7c1bb","component":"SyncMerkleTrieWorker","msg":"MerkleTrieImpl: stopping"}
hubble-hubble-1   | {"level":30,"time":1708519892767,"pid":1,"hostname":"d07795f7c1bb","component":"WatchContractEvent","key":"StorageRegistry","msg":"Stopped watching contract events"}
hubble-hubble-1   | {"level":30,"time":1708519892768,"pid":1,"hostname":"d07795f7c1bb","component":"WatchContractEvent","key":"IdRegistryV2","msg":"Stopped watching contract events"}
hubble-hubble-1   | {"level":30,"time":1708519892768,"pid":1,"hostname":"d07795f7c1bb","component":"WatchContractEvent","key":"KeyRegistryV2","msg":"Stopped watching contract events"}
hubble-hubble-1   | {"level":30,"time":1708519892768,"pid":1,"hostname":"d07795f7c1bb","component":"WatchBlockNumber","msg":"Stopped watching block numbers"}
hubble-hubble-1   | {"level":30,"time":1708519892769,"pid":1,"hostname":"d07795f7c1bb","component":"Engine","msg":"stopping engine"}
hubble-hubble-1   | {"level":30,"time":1708519892777,"pid":1,"hostname":"d07795f7c1bb","component":"Engine","msg":"validation worker thread terminated"}
hubble-hubble-1   | {"level":30,"time":1708519892777,"pid":1,"hostname":"d07795f7c1bb","component":"Engine","msg":"engine stopped"}
hubble-hubble-1   | {"level":30,"time":1708519892798,"pid":1,"hostname":"d07795f7c1bb","component":"Hub","msg":"Hubble stopped, exiting normally"}
hubble-hubble-1   | {"level":30,"time":1708519892798,"pid":1,"hostname":"d07795f7c1bb","msg":"Hub stopped gracefully"}
```

**Comment by sanjayprabhu** [comment]
Could you please grep the logs for "shutting down hub" and post it? I fixed a potential cause in 1.10.2, so please try upgrading and let me know if it still happens.

**Comment by lucasmenendez** [comment]
Yes the 1.10.2 fixes the crash, but the go example still does not work... I am trying to create a bot for [farcaster.vote](https://farcaster.vote/app) and I cannot figure out how to sign the vote to be submitted...

**Comment by sanjayprabhu** [comment]
> @lucasmenendez the go example signs the message data bytes with the ed25519 key [at this location](https://github.com/farcasterxyz/hub-monorepo/blob/main/packages/hub-web/examples/golang-submitmessage/main.go#L64), I believe this is an error and should actually sign the truncated 160-bit (20 byte) blake3 hash as part of [this spec](https://github.com/farcasterxyz/protocol/blob/main/docs/SPECIFICATION.md#2-message-specifications)
> 
> At least, this was the issue I had when developing and testing against the grpc endpoints, and the only way I was able to submit a message to a hub successfully. I'm assuming it's a similar issue

Ah good catch. That is a bug, the example should indeed be signing just the hash. Will fix.

**Comment by lucasmenendez** [comment]
Thanks so much! Its working! https://github.com/vocdoni/votebot/blob/7319a95295520e675091176d81f553f81e601182/api/hub/hub.go#L187
