### ISSUE TITLE
hubble: Repeated crashes on 1.10.6 

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#1762]
**What is the bug?**

We're seeing repeated crashes on hubble due to alchemy RPC timing out

```
hubble-hubble-1  | {"message":"{\"level\":50,\"time\":1709495350524,\"pid\":41,\"hostname\":\"fa79cc04c428\",\"reason\":\"Unhandled Rejection\",\"err\":{\"type\":\"TimeoutError\",\"message\":\"The request took too long to respond.\\n\\nURL: https://opt-mainnet.g.alchemy.com/v2/xxxxxxxxxxxxxxxxxxxxxxx\\nRequest body: {\\\"method\\\":\\\"eth_uninstallFilter\\\",\\\"params\\\":[\\\"0xda34257861b4d8172d4331eb9e36bc3b\\\"]}\\n\\nDetails: The request timed out.\\nVersion: viem@1.12.2\",\"stack\":\"TimeoutError: The request took too long to respond.\\n\\nURL: https://opt-mainnet.g.alchemy.com/v2/xxxxxxxxxxxxx\\nRequest body: {\\\"method\\\":\\\"eth_uninstallFilter\\\",\\\"params\\\":[\\\"0xda34257861b4d8172d4331eb9e36bc3b\\\"]}\\n\\nDetails: The request timed out.\\nVersion: viem@1.12.2\\n    at Object.http (file:///home/node/app/node_modules/viem/utils/rpc.ts:102:24)\\n    at fn (file:///home/node/app/node_modules/viem/clients/transports/http.ts:95:28)\\n    at request (file:///home/node/app/node_modules/viem/clients/transports/http.ts:97:45)\\n    at withRetry.delay.count.count (file:///home/node/app/node_modules/viem/utils/buildRequest.ts:69:24)\\n    at attemptRetry (file:///home/node/app/node_modules/viem/utils/promise/withRetry.ts:34:28)\\n    at retry (file:///home/node/app/node_modules/viem/utils/promise/withRetry.ts:30:9)\",\"details\":\"The request timed out.\",\"metaMessages\":[\"URL: https://opt-mainnet.g.alchemy.com/v2/xxxxxxxxxxxxxxxxxxxxxxx\",\"Request body: {\\\"method\\\":\\\"eth_uninstallFilter\\\",\\\"params\\\":[\\\"0xda34257861b4d8172d4331eb9e36bc3b\\\"]}\"],\"shortMessage\":\"The request took too long to respond.\",\"name\":\"TimeoutError\",\"version\":\"viem@1.12.2\"},\"msg\":\"shutting down hub\"}\n","timestamp":"2024-03-03T19:49:10.524Z","type":"out","process_id":0,"app_name":"hubble"}
```

**Comment by sds** [comment]
We've addressed this in [1.10.9](https://github.com/farcasterxyz/hub-monorepo/releases/tag/%40farcaster%2Fhubble%401.10.9). Thanks for the report!
