### ISSUE TITLE
Older versions of hub-nodejs cannot validate frame action messages created with latest protobufs

### ISSUE THREAD

**Issue by stephancill** [farcasterxyz/hub-monorepo#1942]
**What is the bug?**

Some frame servers are using older versions of hub-nodejs to validate frame messages and are failing to validate messages created with the latest Message protobufs.

**How can it be reproduced? (optional)**

Install an older version of hub-nodejs
```sh
npm install @farcaster/hub-nodejs@0.10.21
```

Create script `index.js`
```js
const { getSSLHubRpcClient, Message } = require("@farcaster/hub-nodejs");

const HUB_URL = process.env["HUB_URL"] || "nemes.farcaster.xyz:2283";
const hubClient = getSSLHubRpcClient(HUB_URL);

// This message was created using the latest `Message` protobuf.js
const messageBytes = "0a59080d10990d1890a4e431200182014a0a16687474703a2f2f6c6f63616c686f73743a333030312f10021a180801121400000000000000000000000000000000000000003a14000000000000000000000000000000000000000112140882173dccc8c18e1d5cd8e5dc01e95440c77d47180122409c62ca15e8d5766b34f9ee5b060533e8eec45f668c28ed3c193528c66ccbdf4a4c6ca8194bcdf05d29a2151c5e2801d579a3c083ea47b407bbebcbf6b9c29a072801322086000f1f279d1780b66fed4bb84c016be2162b3b6416860efb0299adeff9473e";

async function main() {
  const httpResult = await fetch(
    "https://nemes.farcaster.xyz:2281/v1/validateMessage",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/octet-stream",
      },
      body: Buffer.from(messageBytes, "hex"),
    }
  );
  const httpValidationResult = await httpResult.json();
  console.log(httpValidationResult);

  const frameMessage = Message.decode(Buffer.from(messageBytes, "hex"));
  const validateResult = await hubClient.validateMessage(frameMessage);
  console.log(validateResult);
}

main();
```

Run the script
```
node index.js
```

Output (fails validation)
```
$ node index.js
{
  valid: true,
  message: {
    data: {
      type: 'MESSAGE_TYPE_FRAME_ACTION',
      fid: 1689,
      timestamp: 104403472,
      network: 'FARCASTER_NETWORK_MAINNET',
      frameActionBody: [Object]
    },
    hash: '0x0882173dccc8c18e1d5cd8e5dc01e95440c77d47',
    hashScheme: 'HASH_SCHEME_BLAKE3',
    signature: 'nGLKFejVdms0+e5bBgUz6O7EX2aMKO08GTUoxmzL30pMbKgZS83wXSmiFRxeKAHVeaPAg+pHtAe768v2ucKaBw==',
    signatureScheme: 'SIGNATURE_SCHEME_ED25519',
    signer: '0x86000f1f279d1780b66fed4bb84c016be2162b3b6416860efb0299adeff9473e'
  }
}
Err {
  error: HubError: invalid hash. Expected=8,130,23,61,204,200,193,142,29,92,216,229,220,1,233,84,64,199,125,71, computed=69,253,116,217,238,131,17,87,224,64,189,30,164,136,159,85,175,204,7,132
      at fromServiceError (/Users/stephan/environments/mod/pus/validation-repro/node_modules/@farcaster/hub-nodejs/dist/index.js:8431:10)
      at Object.callback (/Users/stephan/environments/mod/pus/validation-repro/node_modules/@farcaster/hub-nodejs/dist/index.js:8448:66)
      at Object.onReceiveStatus (/Users/stephan/environments/mod/pus/validation-repro/node_modules/@grpc/grpc-js/build/src/client.js:192:36)
      at Object.onReceiveStatus (/Users/stephan/environments/mod/pus/validation-repro/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
      at Object.onReceiveStatus (/Users/stephan/environments/mod/pus/validation-repro/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
      at /Users/stephan/environments/mod/pus/validation-repro/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
    errCode: 'bad_request.validation_failure',
    presentable: false,
    [cause]: undefined
  }
}
```

Install latest version
```sh
npm install @farcaster/hub-nodejs@0.11.10
```

Run the script
```
node index.js
```

Output (succeeds):
```
$ node index.js                 
{
  valid: true,
  message: {
    data: {
      type: 'MESSAGE_TYPE_FRAME_ACTION',
      fid: 1689,
      timestamp: 104403472,
      network: 'FARCASTER_NETWORK_MAINNET',
      frameActionBody: [Object]
    },
    hash: '0x0882173dccc8c18e1d5cd8e5dc01e95440c77d47',
    hashScheme: 'HASH_SCHEME_BLAKE3',
    signature: 'nGLKFejVdms0+e5bBgUz6O7EX2aMKO08GTUoxmzL30pMbKgZS83wXSmiFRxeKAHVeaPAg+pHtAe768v2ucKaBw==',
    signatureScheme: 'SIGNATURE_SCHEME_ED25519',
    signer: '0x86000f1f279d1780b66fed4bb84c016be2162b3b6416860efb0299adeff9473e'
  }
}
Ok {
  value: {
    valid: true,
    message: {
      data: [Object],
      hash: <Buffer 08 82 17 3d cc c8 c1 8e 1d 5c d8 e5 dc 01 e9 54 40 c7 7d 47>,
      hashScheme: 1,
      signature: <Buffer 9c 62 ca 15 e8 d5 76 6b 34 f9 ee 5b 06 05 33 e8 ee c4 5f 66 8c 28 ed 3c 19 35 28 c6 6c cb df 4a 4c 6c a8 19 4b cd f0 5d 29 a2 15 1c 5e 28 01 d5 79 a3 ... 14 more bytes>,
      signatureScheme: 1,
      signer: <Buffer 86 00 0f 1f 27 9d 17 80 b6 6f ed 4b b8 4c 01 6b e2 16 2b 3b 64 16 86 0e fb 02 99 ad ef f9 47 3e>,
      dataBytes: undefined
    }
  }
}
```
**Additional context (optional)**
This problem is avoidable for now since the fields causing the problem are `address` and `transactionId` which are only included in transaction frame actions. Excluding these from being hashed when they are undefined might help with backwards compatibility.

**Comment by sanjayprabhu** [comment]
It looks like it's because the frameActionBody.address is set to a non-zero value: 
```
    frameActionBody: {
      url: <Buffer 68 74 74 70 3a 2f 2f 6c 6f 63 61 6c 68 6f 73 74 3a 33 30 30 31 2f>,
      buttonIndex: 2,
      castId: [Object],
      inputText: Uint8Array(0) [],
      state: Uint8Array(0) [],
      transactionId: Uint8Array(0) [],
      address: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01>
    },

```

if address is actually undefined, the hashes should match and it should work even in the older version.

**Comment by sds** [comment]
Closing as the question was answered. Thanks!
