### ISSUE TITLE
Crash on start hubble v1.12.1, Failed to get snapshot 404

### ISSUE THREAD

**Issue by jgresham** [farcasterxyz/hub-monorepo#1986]
**What is the bug?**
Crash  on start after updating hubble to 1.12.1
```json
{
  "level": 60,
  "time": 1714763520994,
  "pid": 1,
  "hostname": "f6aff2b168f7",
  "err": {
    "type": "Error",
    "message": "Failed to start hub: failed to fetch snapshot metadata - Failed to get latest snapshot from https://download.farcaster.xyz/snapshots/MAINNET/DB_SCHEMA_11/latest.json [AxiosError: Request failed with status code 404]",
    "stack": "Error: Failed to start hub\n    at file:///home/node/app/apps/hubble/build/cli.js:540:75\n    at /home/node/app/node_modules/neverthrow/dist/index.cjs.js:113:102\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Command.<anonymous> (file:///home/node/app/apps/hubble/build/cli.js:540:25)\ncaused by: HubError: failed to fetch snapshot metadata - Failed to get latest snapshot from https://download.farcaster.xyz/snapshots/MAINNET/DB_SCHEMA_11/latest.json [AxiosError: Request failed with status code 404]\n    at Hub.attemptCatchupSyncWithSnapshot (file:///home/node/app/apps/hubble/build/hubble.js:500:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Hub.start (file:///home/node/app/apps/hubble/build/hubble.js:263:33)\n    at async Command.<anonymous> (file:///home/node/app/apps/hubble/build/cli.js:540:25)"
  },
  "msg": "Failed to start hub"
}
```

**How can it be reproduced? (optional)**
Start command 
```
podman run -q -d --name hubble-1714763513183 -v "/home/johns/.config/NiceNode/nodes/hubble-1714763513/hub":/home/node/app/apps/hubble/.hub:z -v "/home/johns/.config/NiceNode/nodes/hubble-1714763513/rocks":/home/node/app/apps/hubble/.rocks:z -p 2282:2282/tcp -p 2282:2282/udp -p 2281:2281 --user 0 docker.io/farcasterxyz/hubble:latest node --no-warnings build/cli.js start --ip 0.0.0.0  --gossip-port 2282 --http-api-port 2281 --network 1 -b /dns/nemes.farcaster.xyz/tcp/2282 --eth-mainnet-rpc-url https://eth-mainnet.g.alchemy.com/v2/<key> --l2-rpc-url https://opt-mainnet.g.alchemy.com/v2/<key> --hub-operator-fid 710
```

**Additional context (optional)**
none atm

**Comment by jgresham** [comment]
no longer crashes, no 404 response
