### ISSUE TITLE
shuttle yarn start start leads to redis-related: Err no such key

### ISSUE THREAD

**Issue by Caruso33** [farcasterxyz/hub-monorepo#2056]
**What is the bug?**
After running `yarn start worker` and `yarn start backfill`, `yarn start start` throws a redis related error `ERR no such key`

**How can it be reproduced? (optional)**
just proceeded according to the [shuttle README.md](https://github.com/farcasterxyz/hub-monorepo/blob/main/packages/shuttle/README.md). After running 

**Additional context (optional)**

`yarn start worker` output:

```shell
[10:48:30.773] INFO (535895): Starting worker connecting to: postgres://shuttle:password@0.0.0.0:6541, 0.0.0.0:16379, nemes.farcaster.xyz:2283
```

`yarn start backfill` output:

```shell
[10:48:36.497] INFO (535962): Creating app connecting to: postgres://shuttle:password@0.0.0.0:6541, 0.0.0.0:16379, nemes.farcaster.xyz:2283
[10:48:36.654] INFO (535962): Backfilling fids: 
```

`yarn start start` output:

```shell
(Use `node --trace-warnings ...` to show where the warning was created)
[11:05:46.787] INFO (540027): Creating app connecting to: postgres://shuttle:password@0.0.0.0:6541, 0.0.0.0:16379, nemes.farcaster.xyz:2283
[11:05:46.951] INFO (540027): Starting shuttle
[11:05:47.012] INFO (540027): Migrations up to date
[11:05:47.012] INFO (540027): Starting HubSubscriber shuttle
[11:05:47.121] INFO (540027): HubSubscriber shuttle connected to hub
[11:05:47.124] WARN (540027): No last hub event ID found, starting from beginning
[11:05:47.127] INFO (540027): HubSubscriber shuttle subscribed to hub events (types [9,1,6,2,3], shard: 0/0)

/home/ubuntu/hub-monorepo/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^
ReplyError: ERR no such key
    at parseError (/home/ubuntu/hub-monorepo/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/ubuntu/hub-monorepo/node_modules/redis-parser/lib/parser.js:302:14)
[11:05:57.127] INFO (540027): Starting stream consumer
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Anyone know, what is going wrong here?

**Comment by sds** [comment]
Thanks for the report! Fixed in #2079.

Upgrade to [@farcaster/shuttle@0.4.3](https://github.com/farcasterxyz/hub-monorepo/releases/tag/%40farcaster%2Fshuttle%400.4.3) or newer to get the fix.
