### ISSUE TITLE
Error building shuttle package

### ISSUE THREAD

**Issue by randombishop** [farcasterxyz/hub-monorepo#2059]
**What is the bug?**
Getting error when trying to build package shuttle

**How can it be reproduced? (optional)**
Tried on Ubuntu with both node 21 and 22 with same outcome: 

```
yarn build
yarn run v1.22.22
$ tsup --config tsup.config.ts
CLI Building entry: ./src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.6.3
CLI Using tsup config: /home/na/hub-monorepo/packages/shuttle/tsup.config.ts
CLI Target: node14,chrome79,edge109,firefox102,safari12
CLI Cleaning output folder
ESM Build start
CJS Build start
ESM dist/index.mjs 44.92 KB
ESM ⚡️ Build success in 61ms
CJS dist/index.js 48.64 KB
CJS ⚡️ Build success in 62ms
DTS Build start
src/shuttle/index.ts(1,25): error TS2307: Cannot find module '@farcaster/hub-nodejs' or its corresponding type declarations.

Error: error occured in dts build
    at Worker.<anonymous> (/home/na/hub-monorepo/node_modules/tsup/dist/index.js:2281:26)
    at Worker.emit (node:events:520:28)
    at MessagePort.<anonymous> (node:internal/worker:262:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:816:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)
DTS Build error
RollupError: Failed to compile. Check the logs above.
    at error (/home/na/hub-monorepo/node_modules/rollup/dist/shared/rollup.js:271:30)
    at Object.error (/home/na/hub-monorepo/node_modules/rollup/dist/shared/rollup.js:24642:20)
    at Object.error (/home/na/hub-monorepo/node_modules/rollup/dist/shared/rollup.js:23883:42)
    at generateDtsFromTs (/home/na/hub-monorepo/node_modules/tsup/dist/rollup.js:7484:22)
    at /home/na/hub-monorepo/node_modules/tsup/dist/rollup.js:7491:59
    at _nullishCoalesce (/home/na/hub-monorepo/node_modules/tsup/dist/rollup.js:1:198)
    at Object.transform (/home/na/hub-monorepo/node_modules/tsup/dist/rollup.js:7491:18)
    at /home/na/hub-monorepo/node_modules/rollup/dist/shared/rollup.js:24841:40
src/utils.ts(3,82): error TS2307: Cannot find module '@farcaster/hub-nodejs' or its corresponding type declarations.
src/utils.ts(93,72): error TS2366: Function lacks ending return statement and return type does not include 'undefined'.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by randombishop** [comment]
Figured out i just needed to build the other packages first
-> Build core
-> Build hub-nodejs
Then you can build shuttle.

**Comment by sds** [comment]
Glad you were able to resolve! Thanks for sharing your solution.
