### ISSUE TITLE
bug(hubble): install hubble via docker error

### ISSUE THREAD

**Issue by imtianx** [farcasterxyz/hub-monorepo#2093]
After `docker compose up hubble -d`, the error log in the container:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: MetricError { repr: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }) }', src/statsd.rs:63:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: MetricError { repr: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }) }
    at rsCreateStatsdClient (file:///home/node/app/apps/hubble/src/rustfunctions.ts:90:7)
    at initializeStatsd (file:///home/node/app/apps/hubble/src/utils/statsd.ts:41:3)
    at Command.<anonymous> (file:///home/node/app/apps/hubble/src/cli.ts:402:9)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: MetricError { repr: IoError(Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }) }
    at rsCreateStatsdClient (file:///home/node/app/apps/hubble/src/rustfunctions.ts:90:7)
    at initializeStatsd (file:///home/node/app/apps/hubble/src/utils/statsd.ts:41:3)
    at Command.<anonymous> (file:///home/node/app/apps/hubble/src/cli.ts:402:9)
```

**Comment by Chaoqun-Guo** [comment]
you can try like this.
```bash
docker compose down hubble to delete all containers created before.

docker compose up hubble without "-d" option, then ctrl+c to stop this.

docker compose up hubble -d
```

**Comment by imtianx** [comment]
After executing  `docker compose up hubble` ,it always has the same error.

**Comment by gpolyansky** [comment]
the same

**Comment by thinhnx-omi** [comment]
i got the same error here, somebody can resolve it ?

**Comment by gpolyansky** [comment]
up

**Comment by sds** [comment]
Hey @imtianx, this looks like an issue local to your system or network. The error `failed to lookup address information: Temporary failure in name resolution` suggests an issue with your DNS configuration.

It's really hard to provide support for configuration issues outside the control of Hubble itself, so I'm going to close this since we're not seeing anything like this on our side.

**Comment by hdbg** [comment]
if you have renamed statsd service, make sure that `STATSD_METRICS_SERVER` in .env is pointing to correct service name

**Comment by imtianx** [comment]
> if you have renamed statsd service, make sure that `STATSD_METRICS_SERVER` in .env is pointing to correct service name

I have't renamed statsd service .

**Comment by hdbg** [comment]
> > if you have renamed statsd service, make sure that `STATSD_METRICS_SERVER` in .env is pointing to correct service name
> 
> I have't renamed statsd service .

in short, this is a problem with config of docker network, not system DNS
