### ISSUE TITLE
gRPC issues when backfilling shuttle

### ISSUE THREAD

**Issue by aagoldberg** [farcasterxyz/hub-monorepo#2380]
**What is the bug?**
I'm having gRPC issues that stop me from backfilling the shuttle.

**How can it be reproduced? (optional)**
aagoldberg@shuttle:~/hub-monorepo/packages/shuttle$ POSTGRES_URL=postgres://shuttle:password@0.0.0.0:6541 REDIS_URL=0.0.0.0:16379 HUB_HOST=0.0.0.0:2281 HUB_SSL=false MAX_FID=100 yarn start backfill
yarn run v1.22.22
$ tsx src/example-app/index.ts backfill
[21:05:07.708] INFO (105610): Creating app connecting to: postgres://shuttle:password@0.0.0.0:6541, 0.0.0.0:16379, 0.0.0.0:2281
[21:05:07.760] INFO (105610): Backfilling fids: 
[21:05:07.832] ERROR (105610): Failed to get max fid
/home/aagoldberg/hub-monorepo/packages/hub-nodejs/dist/index.js:10177
  return new import_core.HubError(err2.metadata.get("errCode")[0], context);
         ^

HubError: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
    at fromServiceError (/home/aagoldberg/hub-monorepo/packages/hub-nodejs/dist/index.js:10177:10)
    at Object.callback (/home/aagoldberg/hub-monorepo/packages/hub-nodejs/dist/index.js:10194:66)
    at Object.onReceiveStatus (/home/aagoldberg/hub-monorepo/node_modules/@grpc/grpc-js/src/client.ts:360:26)
    at Object.onReceiveStatus (/home/aagoldberg/hub-monorepo/node_modules/@grpc/grpc-js/src/client-interceptors.ts:458:34)
    at Object.onReceiveStatus (/home/aagoldberg/hub-monorepo/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at <anonymous> (/home/aagoldberg/hub-monorepo/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errCode: undefined,
  presentable: false,
  [cause]: undefined
}

Node.js v21.7.3
error Command failed with exit code 1.

**Additional context (optional)**

Shuttle installation steps: 
https://github.com/farcasterxyz/hub-monorepo/tree/main/packages/shuttle

Also, a problem with 'NVM Install 21':
There is a requirement of 'install nvm 21' in the shuttle install. The version of rimraf, v6, used in the hub-monorepo only works with NVM 20 and 22. Though, when I set the version rimraf to v5, NVM 21 was usable, but still gave me the gRPC bug.

**Comment by aagoldberg** [comment]
gRPC is 2283, whereas rest is usually 2281!
