### ISSUE TITLE
Crash on start hubble v1.15.7, Failed to get snapshot 404

### ISSUE THREAD

**Issue by brucexc** [farcasterxyz/hub-monorepo#2383]
**What is the bug?**
Crash on start after updating hubble to 1.15.7
```json
{
  "app_name": "hubble",
  "message": {
    "level": 60,
    "time": 1729898201744,
    "pid": 29,
    "hostname": "farcaster-hubble-0",
    "err": {
      "type": "Error",
      "message": "Failed to start hub: failed to fetch snapshot metadata - Failed to get latest snapshot from https://download.farcaster.xyz/snapshots/MAINNET/DB_SCHEMA_11/latest.json [AxiosError: Request failed with status code 404]",
      "stack": "Error: Failed to start hub\n    at file:///home/node/app/apps/hubble/src/cli.ts:682:14\n    at /home/node/app/node_modules/neverthrow/dist/index.cjs.js:113:102\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Command.<anonymous> (file:///home/node/app/apps/hubble/src/cli.ts:680:25)\ncaused by: HubError: failed to fetch snapshot metadata - Failed to get latest snapshot from https://download.farcaster.xyz/snapshots/MAINNET/DB_SCHEMA_11/latest.json [AxiosError: Request failed with status code 404]\n    at Hub.attemptCatchupSyncWithSnapshot (file:///home/node/app/apps/hubble/src/hubble.ts:934:18)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at Hub.start (file:///home/node/app/apps/hubble/src/hubble.ts:631:27)\n    at Command.<anonymous> (file:///home/node/app/apps/hubble/src/cli.ts:680:25)"
    },
    "msg": "Failed to start hub"
  },
  "process_id": 0,
  "timestamp": "2024-10-25T23:16:41.788Z",
  "type": "out"
}
```

**How can it be reproduced? (optional)**
Accessed link https://download.farcaster.xyz/snapshots/MAINNET/DB_SCHEMA_11/latest.json , returned 404

**Additional context (optional)**
none

**Comment by runninyeti** [comment]
Same issue here ✋ Looks like this has happened before and a temporary (?) workaround is to add this to your `.env` file:

```
CATCHUP_SYNC_WITH_SNAPSHOT=false
```

Context: https://github.com/farcasterxyz/hub-monorepo/issues/1930#issuecomment-2067744710

**Comment by brucexc** [comment]
> Same issue here ✋ Looks like this has happened before and a temporary (?) workaround is to add this to your `.env` file:
> 
> ```
> CATCHUP_SYNC_WITH_SNAPSHOT=false
> ```
> 
> Context: [#1930 (comment)](https://github.com/farcasterxyz/hub-monorepo/issues/1930#issuecomment-2067744710)

Followed the suggested workaround and added `CATCHUP_SYNC_WITH_SNAPSHOT=false` to the .env file, and it seems to have resolved the issue temporarily.
