### ISSUE TITLE
bug(hubble): ethers throws could not coalesce, filter not found error

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub-monorepo#775]
**What is the bug?**
Testnet user reports many instances of "Error: could not coalesce" in their logs

**How can it be reproduced? (optional)**
Unclear

**Additional context**

```
@TODO Error: could not coalesce error (error={ "code": -32000, "message": "filter not found" }, code=UNKNOWN_ERROR, version=6.2.1)

     at makeError (/home/node/app/node_modules/ethers/src.ts/utils/errors.ts:663:21)

     at JsonRpcProvider.getRpcError (/home/node/app/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:871:16)

     at <anonymous> (/home/node/app/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:423:52)

     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {

   code: 'UNKNOWN_ERROR',

   error: { code: -32000, message: 'filter not found' }

 }
```

**Comment by varunsrin** [comment]
unable to reproduce, but @adityapk00 added more retries to guard against this, closing until we get another repro
