### ISSUE TITLE
bug(hub-web): hub-web returns HubError: NotFound for blank user data

### ISSUE THREAD

**Issue by manan19** [farcasterxyz/hub-monorepo#882]
**What is the bug?**
@farcaster/hub-web returns an error on blank user data

```
Err2 {
  error: HubError: NotFound: 
      at fromServiceError (file:///test/node_modules/@farcaster/hub-web/dist/index.mjs:7782:10)
      at file:///test/node_modules/@farcaster/hub-web/dist/index.mjs:7797:26
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///test/app.js:28:26 {
    errCode: 'not_found',
    presentable: false,
    [cause]: undefined
  }
}
```

**How can it be reproduced? (optional)**
```
const client = getHubRpcClient('https://testnet1.farcaster.xyz:2285', false);
const userDataResult = await client.getUserData({fid: 2, userDataType: 1});
console.log(userDataResult);
```

**Additional context (optional)**

**Comment by manan19** [comment]
@varunsrin I was expecting it to return an empty string instead of an error though. 

But it's possible the fallback-to-empty-string can be at a higher level vs. the functions on Client.
