### ISSUE TITLE
Hubble Log Errors (on v1.2.4)

### ISSUE THREAD

**Issue by philcockfield** [farcasterxyz/hub-monorepo#998]
## Context
A summary of errors showing up in the `hubble` output logs.

Version: `@farcaster/hubble@1.2.4`
Run the hub instance:

     cd apps/hubble
     docker compose up

## Error Output (1)
Padding with a couple of pre/post messages.

```
hubble-hubble-1  | {"level":30,"time":1685145677929,"pid":38,"hostname":"92d2d5311eb3","component":"EthEventsProvider","blockNumber":9070174,"msg":"new block: 9070174"}
hubble-hubble-1  | {"level":40,"time":1685145678314,"pid":38,"hostname":"92d2d5311eb3","component":"Hub","submittedMessage":{"timestamp":1678718471000,"hash":"0x3ab2bf7a5e59453cfd1a7f856f8145452a21bfad","fid":8573,"type":3},"source":"sync","errCode":"bad_request.duplicate","msg":"submitMessage error: message has already been merged"}
hubble-hubble-1  | {"level":30,"time":1685145678314,"pid":38,"hostname":"92d2d5311eb3","component":"SyncEngine","total":1,"success":0,"deferred":0,"errored":1,"msg":"Merged 0 messages during sync with 1 failures"}


hubble-hubble-1  | @TODO Error: could not coalesce error (error={ "code": -32000, "message": "filter not found" }, 
code=UNKNOWN_ERROR, version=6.2.3)
hubble-hubble-1  |     at makeError (/home/node/app/apps/hubble/node_modules/ethers/src.ts/utils/errors.ts:663:21)
hubble-hubble-1  |     at RetryProvider.getRpcError (/home/node/app/apps/hubble/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:871:16)
hubble-hubble-1  |     at <anonymous> (/home/node/app/apps/hubble/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:423:52)
hubble-hubble-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
hubble-hubble-1  |   code: 'UNKNOWN_ERROR',
hubble-hubble-1  |   error: { code: -32000, message: 'filter not found' }
hubble-hubble-1  | }
hubble-hubble-1  | 


{"level":40,"time":1685145679156,"pid":38,"hostname":"92d2d5311eb3","component":"Hub","submittedMessage":{"timestamp":1678718525000,"hash":"0xea9f4802665e53c1ef6f81ffdcd79ad59065daa8","fid":4634,"type":3},"source":"sync","errCode":"bad_request.duplicate","msg":"submitMessage error: message has already been merged"}
hubble-hubble-1  | {"level":30,"time":1685145679157,"pid":38,"hostname":"92d2d5311eb3","component":"SyncEngine","total":1,"success":0,"deferred":0,"errored":1,"msg":"Merged 0 messages during sync with 1 failures"}
hubble-hubble-1  | {"level":40,"time":1685145679787,"pid":38,"hostname":"92d2d5311eb3","component":"Hub","submittedMessage":{"timestamp":1678718531000,"hash":"0x420d637305b58f093fae875d19877b4102305812","fid":758,"type":3},"source":"sync","errCode":"bad_request.duplicate","msg":"submitMessage error: message has already been merged"}
hubble-hubble-1  | {"level":30,"time":1685145679787,"pid":38,"hostname":"92d2d5311eb3","component":"SyncEngine","total":1,"success":0,"deferred":0,"errored":1,"msg":"Merged 0 messages during sync with 1 failures"}
```

**Comment by philcockfield** [comment]
<img width="691" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/185555/e8ca75e1-c778-4ae9-9728-d461f2677128">

**Comment by varunsrin** [comment]
@philcockfield are you seeing these issues in 1.3.3?

**Comment by philcockfield** [comment]
Hey there @varunsrin.
Can confirm that a search of logs when running `1.3.3` does not contains this error. 🌳

<img width="762" alt="image" src="https://github.com/farcasterxyz/hub-monorepo/assets/185555/a9a0096f-321e-4c33-977b-aab1b78d33de">

**Comment by philcockfield** [comment]
Would you like me to close this issue - or leave it to team?  Looks like it's resolved.
